mime ^audio, has mpv = mpv --no-video --term-osd-bar -- "$@"

mime ^text, label editor = ${VISUAL:-$EDITOR} -- "$@"
ext tex|md|markdown|json|yaml|yml|toml|csv|xml|log|conf|ini|rs|vim|sh|bash|zsh|pl|php|sql, label editor = ${VISUAL:-$EDITOR} -- "$@"

label open, flag f = xdg-open "$@"
