#! /usr/bin/perl
use strict;
use warnings;

use Term::ANSIColor;

my @deps = (
  "dot",
  "pdfunite",
  "zathura",

  "gdb-add-index",
  "readelf",

  "fzf",
  "ranger",

  "xsel",
);

for my $dep(@deps) {
  print color('green');
  if (system("which $dep 2> /dev/null") != 0) {
    print color('red'); print "Can't find $dep\n";
  }
}

print color('reset');
