#! /bin/bash

# Use wrcs, which is a wrapper for this script

g_prefix_run= # not used as of now
g_run_mode= # run type (dry or nothing)

function print_usage {

cat <<EOL
You should be using wrcs wrapper unless you know what you're doing.
Usage : rcsync [EXTRA_OPTIONS] -s <tree> -f <from> -t <to>

Options :
-s : tree-directory
-f : syncing from directory
-t : syncing to directory
-d : dry run (Always do this first!)
-c : view diff (this too!)

Brief:
The tree-dir forms the hierarchy of files which would be
the "tree" for synchronization from "from" to "to"
Example : 
To "sync in" your home	:	rcsync -s home/ -f /home/abinav -t to/repo/home
To "sync out" your home	:	rcsync -s home/ -f to/repo/home -t /home/abinav
Note : "sync in" mean "update the git repo from system" You should be doing
this more often.
And "sync out" means "update the system from the git repo". If you are
doing this, then either you have a new system or unsynced system or you
messed up your system big time.
EOL

}


function sanitize_path_string {
	dir=`echo $1 | tr -s /`

	if [[ $dir == '/' ]]; then
		echo -n '/'
	fi
	echo -n $dir | sed 's:/$::' # remove the trailing /
}

function rc_tree_sync {
	if [[ $# -ne 3 ]]; then
		print_usage; exit
	fi	   
	dir_tree=`sanitize_path_string $1`
	dir_from=`sanitize_path_string $2`
	dir_to=`sanitize_path_string $3`

	if [[ ! -d $dir_tree || ! -d $dir_from || ! -d $dir_to ]]; then
		print_usage; exit
	fi

	tree_root_len=`echo -n "$dir_tree" | wc -c`

	files_tree=(`$g_prefix_run find $dir_tree -type f -print |	\
		cut -c1-$(($tree_root_len + 1)) --complement `)

	for f in ${files_tree[@]}; do
		if [[ $g_run_mode == "dry" ]]; then
			echo "$g_prefix_run mkdir -p `dirname ${dir_to}/$f`"
			echo "$g_prefix_run cp -v ${dir_from}/$f `dirname ${dir_to}/$f`"

		elif [[ $g_run_mode == "diff" ]]; then
			echo "diff ${dir_from}/$f ${dir_to}/$f"
			$g_prefix_run diff ${dir_from}/$f ${dir_to}/$f
			echo

		else
			# $f can be a x/y/file so get dirname with it
			$g_prefix_run mkdir -p `dirname ${dir_to}/$f`
			$g_prefix_run cp -v ${dir_from}/$f `dirname ${dir_to}/$f`
		fi
	done
}

while getopts "hcds:f:t:" opt 
do
	case "$opt" in
	c) g_run_mode="diff";;
	d) g_run_mode="dry";;
	h)	print_usage
		exit;;
	s) tree=$OPTARG;;
	f) from=$OPTARG;;
	t) to=$OPTARG;;
	?) 	print_usage
		exit;;
	esac
done

echo; echo "Running($g_prefix_run$g_run_mode by UID:$UID) : rc_tree_sync $tree $from $to"
echo;
rc_tree_sync $tree $from $to
