#! /bin/bash

function print_usage {
cat << ENDCAT
rcsync is a high level wrapper script that uses treesync to sync rc files
between the system and this repo.

Usage: rcsync <profile-selector> <run>

WARNING! Please do a dry run and/or diff before running rcsync, especially when
running sout since it writes over all your system rc files without any prompt.
You have been warned.

<profile-selector>:
-H <profile-name> : work on home/<profile-name>
-S <profile-name> : work syroot/<profile-name> and sysroot/all

Other options:
-d                : does a dry run (when used with -H or -S)
-h                : prints this help

<run>:
diff  : diff in with out
sin   : Sync in with out
sout  : Sync out with in

where, in means this repo and out means the system.  See rcsync -h and the
examples below.

Examples:
rcsync -d -H abinav sin # dry run of sin (sync home/abinav with ~)
rcsync -S y50 diff # does a diff with / and (sysroot/all + sysroot/y50)
rcsync -H abinav sin # does sync in.
rcsync -H abinav sout # does sync out.

ENDCAT
}

while getopts "hdS:H:" opt
do
  case "$opt" in
    S)  profile_type="sys"
      profile_name=$OPTARG;;
    H)  profile_type="home"
      profile_name=$OPTARG;;
    d)  dry="-d";;
    h)  print_usage
      exit;;
    ?)  print_usage
      exit;;
  esac
done

if [[ $profile_type == "home" ]]; then
  in="home/${profile_name}"
  out="$HOME" # '~' breaks when used below TODO: know why!

elif [[ $profile_type == "sys" ]]; then
  sudo="sudo"
  in="sysroot/${profile_name}"
  out="/"
else
  print_usage
  exit
fi

if [[ ! -e $in || ! -e $out ]]; then
  print_usage
  exit
fi

for run_type; do true; done # gets last arg

echo "Performing $run_type : "

if [[ $run_type == "sin" ]]; then
  from=$out
  to=$in
  if [[ $profile_type == "sys" ]]; then
    $sudo ./treesync $dry $diff -s sysroot/all -f / -t sysroot/all
  fi

elif [[ $run_type == "sout" ]]; then
  from=$in
  to=$out
  if [[ $profile_type == "sys" ]]; then
    $sudo ./treesync $dry $diff -s sysroot/all -f sysroot/all -t /
  fi

elif [[ $run_type == "diff" ]]; then
  from=$out
  to=$in # order doesn't matter here
  diff="-c"

  if [[ $profile_type == "sys" ]]; then
    $sudo ./treesync $dry $diff -s sysroot/all -f / -t sysroot/all
  fi

else
  print_usage
  exit
fi

echo "$sudo ./treesync $dry $diff -s $in -f $from -t $to"
$sudo ./treesync $dry $diff -s $in -f $from -t $to
