#! /bin/bash

cd "${0%/*}"

function print_usage {
cat << ENDCAT
rcsync is a high level wrapper script that uses treesync to sync rc files
between the system and this repo.

Usage: rcsync <profile-selector> <run>

WARNING! Please do a dry run and/or diff before running sout since it overwrites
your system rc files without any prompt. You have been warned.

<profile-selector>:
-H <profile-name> : work on home/<profile-name>
-S <profile-name> : work on syroot/<profile-name>

Other options:
-d                : does a dry run (when used with -H or -S)
-h                : prints this help

<run>:
diff  : diff in with out
sin   : sync in with out
sout  : sync out with in

where, in means this repo and out means the system.  So "sin" mean "update this
git repo from system".  And "sout" means "update the system from this git
repo".

Do "sin" if you're a developer of this repo. Do "sout" if you have a new system
or unsynchronized system or you messed up your system big time.

See rcsync -h and the examples below.

Examples:
rcsync -d -H abinavpp sin # dry run of sin (sync home/abinavpp with ~)
rcsync -S y50 diff # does a diff with / and sysroot/y50
rcsync -H abinavpp sin # does a sync in.
rcsync -H abinavpp sout # does a sync out.

ENDCAT
}

while getopts "hdS:H:" opt
do
  case "$opt" in
    S)  profile_type="sysroot"
      profile_name=$OPTARG;;
    H)  profile_type="home"
      profile_name=$OPTARG;;
    d)  dry="-d";;
    h)  print_usage
      exit;;
    ?)  print_usage
      exit;;
  esac
done

if [[ $profile_type == "home" ]]; then
  in="home/${profile_name}"
  out="$HOME" # '~' breaks when used below TODO: know why!

elif [[ $profile_type == "sysroot" ]]; then
  sudo="sudo"
  in="sysroot/${profile_name}"
  out="/"
else
  print_usage
  exit
fi

if [[ ! -e $in || ! -e $out ]]; then
  print_usage
  exit
fi

for run_type; do true; done # gets last arg

echo -e "\033[0;32mPerforming $run_type:\033[0m"

if [[ $run_type == "sin" ]]; then
  from=$out
  to=$in

elif [[ $run_type == "sout" ]]; then
  from=$in
  to=$out

elif [[ $run_type == "diff" ]]; then
  from=$out
  to=$in # order doesn't matter here
  diff="-c"

else
  print_usage
  exit
fi

$sudo ./treesync $dry $diff -s $in -f $from -t $to
