#! /usr/bin/perl

use strict;
use warnings;

my $wget = "wget -q --tries 100 --hsts-file /dev/null";

sub setup_vim {
  system("mkdir -p $ENV{HOME}/.cache/vim/swap");
  system("mkdir -p $ENV{HOME}/.vim");
  system("mkdir -p $ENV{HOME}/.vim/autoload");
  system("mkdir -p $ENV{HOME}/.vim/syntax");
}

sub setup_vimplug {
  system("$wget -O $ENV{HOME}/.vim/autoload/plug.vim "
    . "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim");
  system("vim -i NONE -c 'PlugInstall | quit | quit'");
}

sub setup_llvm {
  my $llvm_repo = "https://raw.githubusercontent.com/llvm/llvm-project/main";

  system("$wget -O $ENV{HOME}/.vim/syntax/llvm.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/llvm.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/mir.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/mir.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/machine-ir.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/machine-ir.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/tablegen.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/tablegen.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/mlir.vim"
    . " $llvm_repo/mlir/utils/vim/syntax/mlir.vim");
}

sub setup_gcc {
  system("$wget -O $ENV{HOME}/.vim/syntax/rtl.vim"
    . " https://raw.githubusercontent.com/utensils/colors.vim/master/rtl.vim")
}

setup_vim;
setup_llvm;
setup_gcc;
setup_vimplug;
