#! /usr/bin/perl

use strict;
use warnings;

my @plugins = (
  "https://github.com/Raimondi/delimitMate.git",
  "https://github.com/scrooloose/nerdtree.git",
  "https://github.com/vim-syntastic/syntastic.git",
  "https://github.com/majutsushi/tagbar.git",
  "https://github.com/tpope/vim-commentary.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/google/vim-searchindex.git",
  "https://github.com/tpope/vim-surround.git",
  "https://github.com/tpope/vim-eunuch.git",
  "https://github.com/gioele/vim-autoswap.git",
  "https://github.com/yegappan/greplace.git",
  "https://github.com/prabirshrestha/vim-lsp.git",
  "https://github.com/prabirshrestha/async.vim" # vim-lsp dependency
);

sub setup_pathogen {
  chdir "$ENV{HOME}/.vim";
  system("rm -rf autoload/ &> /dev/null");
  system("mkdir autoload/");
  system("wget -O autoload/pathogen.vim https://tpo.pe/pathogen.vim");
}

sub setup_plugins {
  chdir "$ENV{HOME}/.vim";
  system("rm -rf bundle/ &> /dev/null");
  system("mkdir bundle/");
  chdir "bundle/";

  foreach my $plugin(@plugins) {
    system("git clone $plugin");
  }

  chdir "..";
}

sub setup_llvm {
  system("cp -r $ENV{HOME}/llvm_dev/main/utils/vim/syntax "
    . "$ENV{HOME}/.vim &> /dev/null");
  system("cp -r $ENV{HOME}/llvm_dev/main/projects/mlir/"
    . "utils/vim/syntax $ENV{HOME}/.vim &> /dev/null");
}

sub setup_vim {
  system("mkdir $ENV{HOME}/.vim &> /dev/null");
}

setup_vim;
setup_llvm;
setup_pathogen;
setup_plugins;


# post plugme
# -----------
# taglist [deprecated in favor of tagbar]
# -------
# comment out
# .*map <buffer> for <Tab>
# to enable <Ctrl-i> up navigation

# vim-surround
# ------------
# comment out :
# imap      <C-G>s <Plug>Isurround
# imap      <C-G>S <Plug>ISurround
