#! /usr/bin/perl

use strict;
use warnings;

my $wget = "wget --no-check-certificate --tries 30 --hsts-file /dev/null";

sub setup_vim {
  system("mkdir -p $ENV{HOME}/.cache/vim/swap");
  system("mkdir -p $ENV{HOME}/.vim");
  system("mkdir -p $ENV{HOME}/.vim/autoload");
  system("mkdir -p $ENV{HOME}/.vim/syntax");
}

sub setup_vimplug {
  system("$wget -O $ENV{HOME}/.vim/autoload/plug.vim "
    . "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim");

  # Headless (-es), which skips .vimrc, so -u loads it. -N because -u alone
  # turns on vi-compatible mode, which can't parse .vimrc. --noplugin: a broken
  # plugin can't block the update. --sync: wait for downloads before qa!.
  system("vim -es -N --noplugin -u $ENV{HOME}/.vimrc -i NONE"
    . " -c 'PlugInstall --sync' -c 'PlugUpdate --sync' -c 'qa!' < /dev/null");
}

sub setup_llvm {
  my $llvm_repo = "https://raw.githubusercontent.com/llvm/llvm-project/main";

  system("$wget -O $ENV{HOME}/.vim/syntax/llvm.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/llvm.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/mir.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/mir.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/machine-ir.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/machine-ir.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/tablegen.vim"
    . " $llvm_repo/llvm/utils/vim/syntax/tablegen.vim");

  system("$wget -O $ENV{HOME}/.vim/syntax/mlir.vim"
    . " $llvm_repo/mlir/utils/vim/syntax/mlir.vim");
}

sub setup_gcc {
  system("$wget -O $ENV{HOME}/.vim/syntax/rtl.vim"
    . " https://raw.githubusercontent.com/utensils/colors.vim/master/rtl.vim")
}

gethostbyname("github.com") or die "not connected to the internet\n";
setup_vim;
setup_llvm;
setup_gcc;
setup_vimplug;
