#! /usr/bin/perl

use strict;
use warnings;
use Sys::Hostname;

sub die_usage {
  print("usage: bkemup /path/to/backup.tar.gz\n");
  exit 1;
}

sub delete_array_elements {
  my ($array_ref, @indices) = @_;

  # Remove indexes from end.
  for (sort { $b <=> $a } @indices) {
    splice(@$array_ref, $_, 1);
  }
}

my $host = hostname();

my $chrome_config_path = "$ENV{HOME}/.config/google-chrome";

my @backup_paths = (
  "$ENV{HOME}/documents",
  "$ENV{HOME}/rc",
  "$ENV{HOME}/proj/my",
  "$ENV{HOME}/www",

  "$ENV{HOME}/.mozilla/",

  "$chrome_config_path/Local State",
  "$chrome_config_path/First Run",
  "$chrome_config_path/Default/Bookmarks",
  "$chrome_config_path/Default/Extensions",
  "$chrome_config_path/Default/Extension Rules",
  "$chrome_config_path/Default/Extension State",
  "$chrome_config_path/Default/Sync Extension Settings",
  "$chrome_config_path/Default/Preferences",
  "$chrome_config_path/Default/Secure Preferences",
  "$chrome_config_path/Default/Local Extension Settings",
  "$chrome_config_path/Default/Local Storage",
);

my $dest = ".";

if (scalar @ARGV > 1) { die_usage(); }

if (scalar @ARGV == 1) { $dest = $ARGV[0]; }

my @ignore_indices;
for my $i (0 .. $#backup_paths) {
  if (! -e $backup_paths[$i]) {
    print "ignoring: $backup_paths[$i]\n";
    push(@ignore_indices, $i);
  }
}

delete_array_elements(\@backup_paths, @ignore_indices);

system("tar", "-c", "-z", "-f", "$host.tar.gz", "-C", "$dest", @backup_paths);
