#!/bin/bash

[[ $# -eq 0 ]] && exit

dir="/sys/class/backlight/"

for f in `/bin/ls "${dir}"`; do
	if [[ `/bin/ls "${dir}${f}" | /bin/grep brightness` ]]; then
		file_cur="${dir}${f}/brightness"
		file_max="${dir}${f}/max_brightness"
		break
	fi
done

if [[ ! -e "${file_cur}" || ! -e "${file_max}" ]]; then
	exit
fi

cur=`sudo /bin/cat "${file_cur}"`
max=`sudo /bin/cat "${file_max}"`
min=0 # I guess...
sign=`echo $val | cut -c1`
val=$1

if [[ $val == "+" || $val == "-" ]]; then # find scale factor
	scale_factor=$((max / 20)) # 20 bri levels
	[[ $scale_factor -eq 0 ]] && scale_factor=1
	val=${val}${scale_factor}
elif [[ "${sign}" != "+" ]] && [[ "${sign}" != "-" ]]; then
	val=+$val
fi

new=$(($cur $val))

[[ "${new}" -lt "${min}" ]] && new=$min
[[ "${new}" -gt "${max}" ]] && new=$max

sudo /bin/tee "${file_cur}" <<< "${new}"
