#! /usr/bin/perl

use strict;
use warnings;

my $invocation_file = "CMakeInvocation";
system ("mkexec $invocation_file");

open(my $fh, '>', $invocation_file) or
  die "Could not open file '$invocation_file' $!";

my @eoi = ('PATH', 'LD_LIBRARY_PATH', 'LIBRARY_PATH',
  'CPATH', 'C_INCLUDE_PATH', 'CPLUS_INCLUDE_PATH');

for my $env (@eoi) {
  if (defined $ENV{$env}) {
    print $fh "# export $env=$ENV{$env}\n";
  }
}

print $fh "\ncmake2 \\\n";
foreach my $i (0 .. $#ARGV) {
  print $fh "  \"$ARGV[$i]\"";
  if ($i == $#ARGV) {
    print $fh "\n"
  } else {
    print $fh " \\\n"
  }
}

splice @ARGV, 0, 0, '-DCMAKE_EXPORT_COMPILE_COMMANDS=1';
system("cmake", @ARGV);
