#! /bin/bash

primary_output=$(xrandr | grep -w "connected primary"  | \
  awk -F' +' '{print $1}')

function die() {
  echo $@ 1>&2
  exit 1
}

[[ ! -n $primary_output ]] && die "Unable to determine primary output"

run=$1; output=$2

[[ $output == "primary" ]] && output=$primary_output

if [[ $run == "on" ]]; then
  if [[ $output == $primary_output ]]; then
    xrandr --output $output --auto
  else
    xrandr --output $output --auto --same-as $primary_output
  fi
elif [[ $run == "off" ]]; then
  xrandr --output $output --off
elif [[ $run == "mode" ]]; then
  xrandr --output $primary_output --mode $1
elif [[ $run == "fixfont" ]]; then
  xrandr --dpi 96
else
  xrandr | grep "connected"
fi
