#! /usr/bin/perl

my $eoi_path = qr/^
  (PATH | LD_LIBRARY_PATH | LIBRARY_PATH |
  C_INCLUDE_PATH | CPLUS_INCLUDE_PATH | CPATH)
  $/x;

my $eoi_extra = qr/^
  (LIBOMP.* | KMP.* | OMP.*)
  $/x;


sub match_env {
  my ($eoi_regex, $new_para) = @_;

  foreach my $var (sort keys(%ENV)) {
    if ($var =~ $eoi_regex) {
      if ($new_para) { print "\n"; $new_para = 0; }
      print "$var = $ENV{$var}\n";
    }
  }
}

match_env($eoi_path);
match_env($eoi_extra, "new_para");
