#! /bin/bash

function die_no_project() {
  echo "project doesn't exist"
  exit 1
}

if [[ $# -eq 0 ]]; then
  die_no_project
fi


proj=$1
bin_dir="$LLVM_DEV/install/$proj/bin"
test ! -d "$bin_dir" && bin_dir="$LLVM_DEV/build/$proj/bin"

lib_dir="$LLVM_DEV/install/$proj/lib"
test ! -d "$lib_dir" && lib_dir="$LLVM_DEV/build/$proj/lib"

if [[ ! -d "$bin_dir" ]]; then
  die_no_project
fi

export PATH="$bin_dir:$PATH"
export LD_LIBRARY_PATH="$lib_dir:$LD_LIBRARY_PATH"

shift
$@
