#! /bin/bash

function has_gdbidx() {
	local elfout=$(readelf -S "$1" | egrep "\.gdb_index")

	if [[ -n $elfout ]]; then
		return 0;
	fi
	return 1;
}

function is_elf() {
    if [[ $(file "$1") =~ ^.*ELF.*$ ]]; then
        return 0;
    fi

    return 1;
}

function set_gdbidx() {
	local arg preserve_ts
	if [[ $1 == "-p" ]]; then
		preserve_ts="true"
		shift;
	fi

	for arg in "$@"; do
		local orig_ts=$(stat -c %Y "$arg")

        if test -L "$arg" || ! is_elf "$arg"; then
           continue
        fi

		if has_gdbidx "$arg"; then
			continue
		fi

		echo "Setting .gdb_index for $arg"
		gdb-add-index "$arg"
		if [[ $preserve_ts == "true" ]]; then
			touch -m -d @${orig_ts} $arg
		fi
	done
}

function set_llvm_gdbidx() {
    bin_dir="$LLVM_DEV/build"
    lib_dir="$LLVM_DEV/build"

    if [[ $1 == "-i" ]]; then
        shift
	    bin_dir="$LLVM_DEV/install"
        lib_dir="$LLVM_DEV/install"
    fi

    bin_dir="${bin_dir}/$1/bin"
    lib_dir="${bin_dir}/$1/lib"

    if [[ ! -d "$bin_dir" || ! -d "$lib_dir" ]]; then
        echo "unknown project"
        return
    fi

    gdbi bin_dir ! -name "*.o"
    gdbi lib_dir -maxdepth 1 ! -name "*.o"
}

set_llvm_gdbidx $@
