#! /bin/bash

# usage: llvmb <project> [the-part-after-ninja/make]

orig_path="$PATH"
orig_ldlp="$LD_LIBRARY_PATH"
orig_lp="$LIBRARY_PATH"

export PATH="$RESET_PATH"
export LD_LIBRARY_PATH="$RESET_LD_LIBRARY_PATH"
export LIBRARY_PATH="$RESET_LIBRARY_PATH"

build_dir="$LLVM_DEV/build/$1"
n_cores=$(nproc --all || getconf _NPROCESSORS_ONLN || echo 1)

# be nice to your colleague
if ! am_i_home; then
    n_cores=$((n_cores / 1))
fi

if [[ ! -d "$build_dir" || $# -eq 0 ]]; then
    echo "project doesn't exist"
    exit 1
fi

shift;
cd "$build_dir"

if [[ -e build.ninja ]]; then
    ninja $@
elif [[ -e Makefile ]]; then
    make -j ${n_cores} $@
fi

ret=$?

cd - 1> /dev/null
exit $ret
