#! /bin/bash

xterm \
  +dc `# xterm*dynamicColors` \
  -sl 4096 `# xterm*saveLines` \
  -font '*-fixed-*-*-*-20-*' `# xterm*font` \
  -u8 `# xterm*utf8` \
  -xrm 'xterm*vt100.utf8Fonts: true' \
  -xrm 'xterm*vt100.allowBoldFonts: false' \
  -xrm 'xterm*vt100.utf8: true' \
  -xrm 'xterm*vt100.utf8Title: true' \
  -geometry '159x41' # xterm*vt100.geometry
