#! /bin/bash

xterm \
  -u8 \
  -xrm 'xterm*dynamicColors: true' \
  -xrm 'xterm*saveLines: 4096' \
  -xrm 'xterm*font: *-fixed-*-*-*-20-*' \
  -xrm 'xterm*vt100.utf8Fonts: true' \
  -xrm 'xterm*vt100.allowBoldFonts: false' \
  -xrm 'xterm*vt100.utf8: true' \
  -xrm 'xterm*vt100.utf8Title: true' \
  -xrm 'xterm*vt100.geometry 159x41'
