#! /bin/bash

function die() { echo "$@" 1>&2; exit 1; }

[[ ! $# -ge 1 ]] && die "Usage: pjb <project> <build-cmd>"

pj="$1"; shift
build_dir="~/pj/build/$pj"
[[ ! -d "$build_dir" ]] && die "Project doesn't exist."
cd "$build_dir"

export PATH="$RESET_PATH"
export LD_LIBRARY_PATH="$RESET_LD_LIBRARY_PATH"
export LIBRARY_PATH="$RESET_LIBRARY_PATH"
export CPATH="$RESET_CPATH"

if [[ -e build.ninja ]]; then
  ninja "$@"

elif [[ -e Makefile ]]; then
  make "$@"
fi
