#! /usr/bin/perl
use strict;
use warnings;

my @deps = (
  "dot",
  "pdfunite",
  "zathura",

  "gdb-add-index",
  "readelf",

  "fzf",
  "ranger",

  "xclip"
);

for my $dep(@deps) {
  if (system("which $dep &> /dev/null")) {
    print "$dep not installed!\n";
  }
}
