#! /bin/bash

function die { echo "$@" 1>&2; exit 1; }

function print_usage {
cat << ENDCAT
Usage: rcsync <cmd> <opt>

<cmd>:
  - in: Update the rc repository.
  - out: Update the corresponding external tree.
  - diff: View diff.

<opt>
  - -H <profile>: Add home/<profile> to synchronization.
  - -S <profile>: Add sysroot/<profile> to synchronization.
ENDCAT
}

function print_usage_and_exit { print_usage; exit 0; }

function print_usage_and_die { print_usage; exit 1; }

cd "${0%/*}/.."
cmd=$1
[[ $cmd =~ (in|out|diff) ]] && shift

while getopts "hH:S:" opt
do
  case "$opt" in
    h)
      print_usage_and_exit;;
    S)
      trees+=("sysroot/$OPTARG");;
    H)
      trees+=("home/$OPTARG");;
    ?)
      print_usage_and_die;;
  esac
done

for tree in "${trees[@]}"; do
  if [[ "$tree" =~ ^sysroot/ ]]; then
    out='/'
  elif [[ "$tree" =~ ^home/ ]]; then
    out="$HOME"
  fi

  if [[ $cmd == 'in' ]]; then
    run/treesync -t "$tree" -s "$out" -d "$tree"

  elif [[ $cmd == 'out' ]]; then
    run/treesync -t "$tree" -s "$tree" -d "$out"

  elif [[ $cmd == 'diff' ]]; then
    run/treesync -t "$tree" -s "$tree" -d "$out" -c
  fi
done
