#! /bin/bash

function main {
    local dir="."

    if [[ $# -ne 1 ]]; then
        dir="$1"
    fi

    find $dir -type f -exec sudo chmod 0644 {} \;
    find $dir -type d -exec sudo chmod 0755 {} \;
}

main "$@"
