#! /bin/bash

function spun {
  if [[ `expr match "$1"  "^[[:print:]]*\ .*"` -ne 0 ]]; then
    echo "$1" | sed 's/ /_/g' | xargs -I {} mv "${1}" {}
  fi
}

if [[ "$#" -eq 0 ]]; then
  echo "Usage : spun <dir/file>"
  echo "makes all filename at depth 1 of dir to have '_' instead of ' '"
  exit
fi

for d in "$@"
do
  # if not dir
  if [[ ! -d "${d}" ]]; then
    spun "$d"
    continue
  fi

  # if dir
  for f in ${d}/*
  do
    spun "$f"
  done

done
