#! /usr/bin/perl

use strict;
use warnings;

use Getopt::Long;

my $profile = shift @ARGV;

GetOptions(
  "b=s" => \my $opt_bg_col,
  "f=s" => \my $opt_fg_col,
  "t=s" => \my $opt_target,
  "help" => \my $opt_help)
  or die "Error parsing cmdline";

sub set_term {
  my ($bg_col, $fg_col, $pty) = @_;

  $bg_col = "\e]11;$bg_col\007";
  $fg_col = "\e]10;$fg_col\007";
  open(my $fh, '>', $pty) or return;
  print({$fh} $bg_col . $fg_col);
  close($fh);
}

sub set_all_term {
  my ($bg_col, $fg_col) = @_;
  foreach my $pty(</dev/pts/*>) {
    next if $pty !~ /[0-9]$/;
    set_term($bg_col, $fg_col, $pty);
  }
}

if ($profile eq 'term') {
  if (defined($opt_target)) {
    set_term($opt_bg_col, $opt_fg_col, $opt_target);

  } else {
    set_all_term($opt_bg_col, $opt_fg_col);
  }
}
