#! /usr/bin/perl

use strict;
use warnings;

use Getopt::Long;

my $profile = shift @ARGV;

GetOptions(
  "b=s" => \my $opt_bg_col,
  "f=s" => \my $opt_fg_col,
  "help" => \my $opt_help)
  or die "Error parsing cmdline";

sub set_term {
  my ($bg_col, $fg_col) = @_;

  $bg_col = "\e]11;$bg_col\007";
  $fg_col = "\e]10;$fg_col\007";
  foreach my $pty(</dev/pts/*>) {
    next if $pty !~ /[0-9]$/;
    system("echo -ne \"$bg_col\" > $pty");
    system("echo -ne \"$fg_col\" > $pty");
  }
}

set_term($opt_bg_col, $opt_fg_col)  if ($profile eq 'term');
