#! /bin/bash

function vdot {
	local i=0 f

	template=$(mktemp -tu vdot__def__XXXXXX);

	for f in "$@"; do
		dot -Tpdf "$f" -o "$template$((i++)).pdf"; done

	pdfunite ${template}[0-9]*.pdf ${template}.pdf;

	for f in ${template}[0-9]*.pdf; do
		rm $f; done
	
	zathura ${template}.pdf
	rm ${template}.pdf
}

vdot $@
