#! /bin/bash

# See https://unix4lyfe.org/xterm/

this=`basename $0`

path_xterm='/usr/bin/xterm'
[ -x $HOME_BIN/xterm ] && path_xterm=$HOME_BIN/xterm

cmd="$path_xterm
  -u8
  -xrm 'xterm*background: black'
  -xrm 'xterm*foreground: white'
  -xrm 'xterm*dynamicColors: true'
  -xrm 'xterm*saveLines: 4096'
  -xrm 'xterm*vt100.geometry 159x41'
  -xrm 'xterm*vt100.utf8: true'
  -xrm 'xterm*vt100.utf8Fonts: true'
  -xrm 'xterm*vt100.utf8Title: true'
  -xrm 'xterm*mainMenu*background: black'
  -xrm 'xterm*mainMenu*foreground: white'
  -xrm 'xterm*vtMenu*background: black'
  -xrm 'xterm*vtMenu*foreground: white'
  -xrm 'xterm*fontMenu*background: black'
  -xrm 'xterm*fontMenu*foreground: white'"

# To send alt+ keybindings as <esc><something> (which is how most modern
# linux-terminals behave)
# -xrm 'xterm*eightBitInput: false'

# To make the font size 13 fit better
# -xrm 'xterm*scaleHeight: 0.9'

if [ $this == 'minxterm' ]; then
  cmd+="
    -xrm 'xterm*font: *-fixed-*-*-*-20-*'
    -xrm 'xterm*vt100.allowBoldFonts: false'"
else
  cmd+="
    -xrm 'xterm*vt100.faceName: *:size=12:antialias=true'"
fi

cmd=$(echo $cmd)
exec bash -c "$cmd"
