#! /bin/bash

dev="/dev/snd/hwC1D0"

if [[ $1 == "on" ]]; then
	hda-verb $dev "0x17" "SET_POWER" "0x0"
	hda-verb $dev "0x1a" "SET_POWER" "0x0"

	hda-verb $dev "0x17" "0x300" "0xb000"
	hda-verb $dev "0x17" "0x707" "0x40"

	hda-verb $dev "0x1a" "0x707" "0x25"

elif [[ $1 == "off" ]]; then
	hda-verb $dev "0x1a" "0x707" "0x20"
fi
